---
- name: 
    Update apt cache
  become: 
    true
  apt: 
    update_cache=yes 
    cache_valid_time=3600

- name: 
    Install required software
  become: 
    true
  apt: 
    name={{ item }} 
    state=present
  loop: 
    ["apache2",
    "mysql-server",
    "php5-mysql",
    "php5",
    "libapache2-mod-php5",
    "php5-mcrypt",
    "python-mysqldb"]
